// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductInformation.Models;

namespace ProductInformation.Migrations
{
    [DbContext(typeof(ProductInfoContext))]
    partial class ProductInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProductInformation.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("category");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "Utencil"
                        },
                        new
                        {
                            ID = -2,
                            Name = "Stationary"
                        },
                        new
                        {
                            ID = -3,
                            Name = "Paint"
                        });
                });

            modelBuilder.Entity("ProductInformation.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID")
                        .HasName("FK_Product_Category");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            CategoryID = -1,
                            Name = "Spoon"
                        },
                        new
                        {
                            ID = -2,
                            CategoryID = -1,
                            Name = "Knife"
                        },
                        new
                        {
                            ID = -3,
                            CategoryID = -1,
                            Name = "Ladle"
                        },
                        new
                        {
                            ID = -4,
                            CategoryID = -2,
                            Name = "Paper"
                        },
                        new
                        {
                            ID = -5,
                            CategoryID = -2,
                            Name = "Notebook"
                        });
                });

            modelBuilder.Entity("ProductInformation.Models.Product", b =>
                {
                    b.HasOne("ProductInformation.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .HasConstraintName("FK_Product_Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
